In [4]:
import numpy as np

In [15]:
def transpose_matrix(matrix):
    return np.array([[matrix[j][i] for j in range(len(matrix))] 
                    for i in range(len(matrix[0]))])

In [5]:
def get_minor_matrix(matrix, i, j):
    return [[matrix[row][col] for col in range(len(matrix)) if col != j]
            for row in range(len(matrix)) if row != i]

In [17]:
def determinant_recursive(matrix):
    if len(matrix)==2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    determinant = 0
    for i in range(len(matrix)):
        minor = get_minor_matrix(matrix, 0, i)
        determinant += ((-1)**i) * matrix[0][i] * determinant_recursive(minor)
    return determinant

In [11]:
a = np.array([2, 3, 6, 7, 4, 5, 6, 9, 23])
a = a.reshape(3, 3)
print(determinant_recursive(a))

-13


In [10]:
def create_cofactor_matrix(matrix):
    cofactor_matrix = []
    for i in range(len(matrix)):
        row = []
        for j in range(len(matrix)):
            minor_matrix = get_minor_matrix(matrix, i, j)
            row.append((-1)**(i+j) * determinant_recursive(minor_matrix))
        cofactor_matrix.append(row)
    # print(cofactor_matrix)
    return np.array(cofactor_matrix)

In [12]:
a = np.array([1, 3, 2, -2, 4, 1, 5, -1, 3])
a= a.reshape(3,3)
print(create_cofactor_matrix(a))

[[ 13  11 -18]
 [-11  -7  16]
 [ -5  -5  10]]


In [13]:
def calculate_inverse_matrix(matrix):
    cofactor_matrix = create_cofactor_matrix(matrix)
    adjoint = transpose_matrix(cofactor_matrix)
    determinant = determinant_recursive(matrix)
    if determinant == 0:
        print("Matrix is singular")
        return None
    return adjoint/determinant
    

In [18]:
b=np.array([1,2,3,4,2,3,4,1,3,4,1,2,4,1,2,3])
b = b.reshape(4,4)

In [19]:
calculate_inverse_matrix(b)

array([[-0.225,  0.025,  0.025,  0.275],
       [ 0.025,  0.025,  0.275, -0.225],
       [ 0.025,  0.275, -0.225,  0.025],
       [ 0.275, -0.225,  0.025,  0.025]])