In [1]:
import numpy as np

In [2]:
3+2

5

Exploratory Data Analysis (EDA)

In [4]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
num.shape

(9,)

In [103]:
num.size

9

In [6]:
num.ndim

1

In [7]:
num.reshape(3, 3) #actual array not modified

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
num.reshape(9, 1) #column vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
num.reshape(1, 9) #row vector

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
num_2d = num.reshape(3, 3)

In [15]:
ones_matrix = np.ones((3, 3))

In [16]:
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zeros_matrix = np.zeros((4, 3), dtype=float)

In [23]:
zeros_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(1, 10, 2) #start, end, step

array([1, 3, 5, 7, 9])

In [106]:
np.linspace(1, 10, 20) #start, end, size

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [26]:
i3 = np.eye(3, dtype=int)

In [27]:
i3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
empty_matrix = np.empty((4, 3), dtype=int) ## creating an empty array with garbage values

In [33]:
empty_matrix

array([[      2532997786984,                  64,                   0],
       [                  0,   28429264705552384, 7293916272120587568],
       [7089852393629038642, 3617573812442313009, 7292225419936490594],
       [3835150873554149682, 4049969056503652656, 3834927475061056056]])

In [34]:
num_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
num_2d.T #num_2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
num_2d > 3 #boolean indexing

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
num_2d[num_2d > 3] #using boolean indexing to filter

array([4, 5, 6, 7, 8, 9])

In [40]:
x1 = np.random.randint(1, 10)

In [45]:
x1

8

In [46]:
np.random.seed(0)

In [ ]:
x1 = np.random.randint(5, 10, 3) # defining 1 dimension

In [ ]:
print(x1)

[8 7 9]


In [ ]:
x1 = np.random.randint(5, 10, (3, 3)) # defining 2 dimensions using postional arg

In [53]:
print(x1)

[[5 5 9]
 [7 6 5]
 [6 6 5]]


In [54]:
x2 = np.random.randint(5, 10, size = (3, 3, 5)) #defining 3 dimensions using keyword arg

In [55]:
print(x2)

[[[6 9 8 5 8]
  [5 7 8 5 6]
  [8 8 8 5 6]]

 [[6 6 5 7 9]
  [8 8 7 9 7]
  [5 5 9 5 9]]

 [[6 9 6 7 7]
  [5 6 6 6 6]
  [8 8 7 8 5]]]


In [56]:
x3 = np.random.randint(5, 10, size=(10))

In [58]:
print(x3)

[8 9 6 7 9 8 9 9 9 8]


In [57]:
x3[2:7]

array([6, 7, 9, 8, 9], dtype=int32)

In [ ]:
x3[::-1] #reverse

array([8, 9, 9, 9, 8, 9, 7, 6, 9, 8], dtype=int32)

In [63]:
x1

array([[5, 5, 9],
       [7, 6, 5],
       [6, 6, 5]], dtype=int32)

In [78]:
x = np.random.randint(5, 10, (5, 5))

In [79]:
x

array([[7, 8, 7, 8, 7],
       [6, 7, 8, 8, 8],
       [7, 8, 9, 6, 7],
       [8, 6, 7, 6, 9],
       [7, 8, 5, 8, 7]], dtype=int32)

In [80]:
x[1:3, 2:4]

array([[8, 8],
       [9, 6]], dtype=int32)

Lamba Functions

In [ ]:
#lambda arg : expression
p = lambda p : p + 10

In [70]:
"""
Define a lambda function that takes x as an argument and returns the value added 10
"""
p = lambda p : p + 10

In [71]:
print(p(5))

15


#### Higher order functions

Map

In [96]:
num1 = np.array([1, 3, 5, 7, 9])

In [91]:
mapped_num = np.array(list(map(lambda x: x+1, num1)))

In [99]:
mapped_num

array([ 2,  4,  6,  8, 10])

Filter

In [100]:
num2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
filtered_num = np.array(list((filter(lambda x : x % 2 == 0, num2))))

In [102]:
filtered_num

array([2, 4, 6, 8])