In [4]:
import numpy as np

In [ ]:
def svd(matrix):
    A_transpose_A = np.dot(matrix.T, matrix)

    eigen_values, eigen_vector = np.linalg.eig(A_transpose_A)
    
    # singular value = sqrt(eigen_value)
    sigma = np.sqrt(np.abs(eigen_values))
    
    #sorting in singular values in descending order
    sigma = sigma[np.argsort(-sigma)]
    
    #ordering eigen vector columns based on descending indices of sigma
    eigen_vector = eigen_vector[:, np.argsort(-sigma)]

    # Left Singular Vector, U = A.V/sigma
    U = np.dot(matrix, eigen_vector) / sigma
    
    sigma_matrix = np.diag(sigma)
    
    return U, sigma_matrix, eigen_vector.T

In [22]:
def verify_svd(lhs, U, Sigma, V_T):
    rhs = np.dot(U, np.dot(Sigma, V_T))
    return np.allclose(lhs, rhs)

In [24]:
if __name__ == "__main__":
    # A = np.array([[3, 1],
    #               [1, 3]])
    
    A = np.array([[1, 3, 6],
                  [3, 6, 8],
                  [9, 1, 5]])

    eigvals, eigvecs = np.linalg.eig(np.dot(A.T, A))
    print("Eigenvalues:")
    print(eigvals)
    print("\nEigenvectors:")
    print(eigvecs)

    # Compute SVD
    U, Sigma, V_T = svd(A)
    print("\nU:")
    print(U)
    print("\nSigma:")
    print(Sigma)
    print("\nV.T:")
    print(V_T)

    is_verified = verify_svd(A, U, Sigma, V_T)
    print("\nDoes the relation hold?")
    print("Yes" if is_verified else "No")

Eigenvalues:
[217.45646188  43.18377272   1.35976541]

Eigenvectors:
[[ 0.5357959   0.81240305 -0.23005226]
 [ 0.40136374 -0.48476698 -0.77711526]
 [ 0.74285254 -0.32404053  0.58580529]]

U:
[[ 0.42023818 -0.39354275  0.81763316]
 [ 0.67530971 -0.46621726 -0.57148776]
 [ 0.60609955  0.79231659  0.06984095]]

Sigma:
[[14.74640505  0.          0.        ]
 [ 0.          6.57143612  0.        ]
 [ 0.          0.          1.16608979]]

V.T:
[[ 0.5357959   0.40136374  0.74285254]
 [ 0.81240305 -0.48476698 -0.32404053]
 [-0.23005226 -0.77711526  0.58580529]]

Does the relation hold?
Yes
